export {default as Login} from "./macro/Login"
export {default as Signup} from "./macro/Signup"
export {default as DoctorCard} from "./micro/DoctorCard"
export {default as HospitalCard} from "./micro/HospitalCard"
// export {default as Login} from "./macro/Login"
// export {default as Signup} from "./macro/Signup"